driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.3
  # - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[managed_directory::test]
      - recipe[managed_directory::test_directories]
    attributes:
