---
driver:
  name: dokken

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  root_path: '/opt/verifier'

platforms:
  - name: chef-14
    driver:
      image: dokken/centos-7
      chef_version: 14
  - name: chef-15
    driver:
      image: dokken/centos-7
      chef_version: 15
  - name: chef-latest
    driver:
      image: dokken/centos-7
      chef_version: latest

suites:
  - name: default
    run_list:
      - recipe[test-managed_directory::test]
      - recipe[test-managed_directory::test_directories]
    attributes:
