---
driver:
  name: dokken
  chef_version: 14

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-6
    driver:
      image: dokken/centos-6
  - name: centos-7
    driver:
      image: dokken/centos-7

suites:
  - name: default
    run_list:
      - recipe[managed_directory::test]
      - recipe[managed_directory::test_directories]
    attributes:
